apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    reloader.stakater.com/match: "true"
  name: pod-configmap-env
data:
  REGION: us-east-1
  ECR_REPOSITORY: 123456789.dkr.ecr.us-east-1.amazonaws.com/pod
  SECRET_NAME: regcred
  NAMESPACE_NAME: {{ .Release.Namespace }}
  DOCKER_SECRET_NAME: regcred
